#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.4
# In conjunction with Tcl version 8.6
#    Dec 09, 2016 09:39:17 PM


import sys
import time
import threading
import Queue
import MAVComms
import missionPayload

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1
	
def init(top, gui, *args, **kwargs):
    global w, top_level, root, onMission
    w = gui
    top_level = top
    root = top
    onMission = False
	
def setupScreenUpdating():
    global scrQueue, q_lock, scrThread
    print 'Starting screen-updating'
    #setup a queue for updates, 20 items long
    scrQueue = Queue.Queue(20)
    #set q_lock to prevent multiple routines updating the queue at the same time
    q_lock = threading.Lock()
    #start a thread to deal with updating the GUI
    scrThread = threading.Thread(target=screenUpdates)
    scrThread.setDaemon(True) #ie when the module exits: kill thread
    scrThread.start()
    with q_lock:
        scrQueue.put(['EntryStatus','Screen update activated'])
	
def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global missiontype
    missiontype = IntVar()

def CloseWindow():
    print('UCLRUASNAV2_support.CloseWindow')
    sys.stdout.flush()
    destroy_window()
	
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def startMission():
    global q_lock, onMission
    missionNo = missiontype.get()
    if(missionNo == 1 and onMission!= True):
        print 'starting mission'
        onMission = True
        with q_lock:
            scrQueue.put(['EntryStatus','Starting payload mission'])
        VecCon = startMAVComms()
        if(VecCon is not None):
            missionPayload.startMission(VecCon, GPSTarget)
            missionThread = threading.Thread(target=missionReply)
            missionThread.setDaemon(True) #ie when the module exits: kill thread
            missionThread.start()
        else:
            print('Could not connect to MAV')

def missionReply(mission):
    while(missionPayload.dropped == False):
        time.sleep(1)
        pass
    
    with q_lock:
        scrQueue.put(['EntryStatus','Payload Deployed'])

def startMAVComms():
    VecCon = MAVComms.MAVconnect('udp:127.0.0.1:14551')
    if(VecCon.ConnErrFlag != True):
        with q_lock:
            scrQueue.put(['EntryStatus','Connected to MAV'])
        return VecCon
    else:
        with q_lock:
            scrQueue.put(['EntryStatus','Error connecting to MAV'])
        return None

def screenUpdates():
    #syntax is scrQueue.put(element to update, new value)
    global w, q_lock, scrQueue
    print 'Screen update thread activated'
    time.sleep(1)
    data = ''
    while 1:
        with q_lock:
            if not scrQueue.empty():
                data = scrQueue.get()
                #Is this an entry - if so use this method. Further methods will be written for other elements
                if(data[0].find('EntryStatus') == 0): 
                    elementToUpdate = getattr(w, data[0])
                    elementToUpdate.delete(1.0, END)
                    elementToUpdate.insert(1.0, data[1])
                elif(data[0].find('Entry') == 0): 
                    elementToUpdate = getattr(w, data[0])
                    elementToUpdate.delete(0, END)
                    elementToUpdate.insert(0, data[1])
            if data == 'quit':
                break 

if __name__ == '__main__':
    import UCLRUASNAV2
    UCLRUASNAV2.vp_start_gui()
